query getContract($id: String!){
    getContract(id: $id){
        id
        address
        code
        details{
            contractCreatedDate
            contractName
            customerInfo{
                address
                name
                phoneNumber
                representative
                type
            }
        }
        fileUrl
        hireDate
        hireEndDate
        status
        totalPrice
        paymentIntentId
        type
        createdAt
        updatedAt
        contractEvent{
            id
            contractId
            eventId
            event{
                id
                isPublic
                isUsed
                detail
                name
                description
                thumbnail
            }
            contractEventServiceItems{
                amount
                id
                contractEventId
                serviceItemId
                serviceItem{
                    id
                    name
                    price
                    description
                    totalQuantity
                    service{
                        id
                        images
                    }
                }
            }


        }
        contractServiceItems{
            id
            amount
            hireDate
            hireEndDate
            serviceItemId
            serviceItem{
                id
                name
                price
                totalQuantity
                description
                service{
                    id
                    images
                }
            }
        }

    }
}