query getContracts($queryParams: QueryFilterDto!){
    getContracts(queryParams: $queryParams){
        meta{
            ...MetaFragment
        }
        items{
            id
            address
            code
            details{
                contractCreatedDate
                contractName
                customerInfo{
                    address
                    name
                    phoneNumber
                    representative
                    type
                }
            }
            fileUrl
            hireDate
            hireEndDate
            status
            totalPrice
            paymentIntentId
            type
            createdAt
            updatedAt
        }
    }
}