query getMyCart {
  getMyCart {
    id
    userId
    cartItems {
      id
      serviceItemId
      hireDate
      hireEndDate
      amount
      serviceItem {
        id
        name
        price
        isPublished
        serviceId
        description
        totalQuantity
        updatedAt
        createdAt
        service {
          id
          images
          type
        }
      }
      createdAt
      updatedAt
    }
  }
}
