query getService($id: String!) {
    getService(id: $id) {
        id
        name
        description
        images
        type
        detail
        isPublished
        createdAt
        updatedAt
        serviceItems {
            id
            name
            price
            isPublished
            isUsed
            serviceId
            description
            totalQuantity
            updatedAt
            createdAt
        }
    }
}
