query getServices($query: QueryFilterDto!) {
    getServices(query: $query) {
        meta {
            ...MetaFragment
        }
        items {
            id
            name
            description
            images
            type
            detail
            isPublished
            createdAt
            updatedAt
            serviceItems {
                id
                name
                price
                isUsed
                isPublished
                serviceId
                description
                totalQuantity
                updatedAt
                createdAt
            }
        }
    }
}
